### ISSUE TITLE
Difficult to see with some desktop themes

### ISSUE THREAD

**Issue by limburgher** [tstriker/apx#14]
apx is almost invisible when using the default theme on GNOME 3.
![screenshot from 2016-07-10 16-37-48](https://cloud.githubusercontent.com/assets/2363820/16995375/a211f450-4e71-11e6-8b48-1caf5fb08da7.png)

**Comment by rapgro** [comment]
Reproducible for me, also in LXQt with dark theme. 
Possible solution: Maybe enforce a dark background in Gtk independent from the active theme setting.

**Comment by tstriker** [comment]
oh boy, how did that happen! :)

**Comment by tstriker** [comment]
thanks @rapgro!
